### ISSUE TITLE
Lenguaje de programación de desarrollo

### ISSUE THREAD

**Issue by ChinChainis** [blancagiron/SeguraSenior#7]
Buenas Blanca, antes de empezar a comentar sobre tu milestone 0 deberíamos de tener claro qué lenguaje de programación vas a usar para desarrollar código. He leído que quieres usar python ¿Algún motivo específico para este lenguaje o te has replanteado otro desde que escribiste eso?

**Comment by blancagiron** [comment]
Hola :) en principio había pensado en Python porque estoy cómoda con él y me pareció adecuado para el problema, pero aun así estoy abierta a explorar otros lenguajes. También había pensado en Go, o si tienes alguna sugerencia o ves que hay uno que se adapte mejor !

**Comment by ChinChainis** [comment]
Veo que tu proyecto se basa mucho en obtener información de distintos lugares de la nube, si bien python tiene diversas funciones de procesamiento de texto, Go está bastante orientado al desarrollo web y tiene múltiples funciones de extración de información de páginas online. Creo que te recomendaría Go para además poder aplicar desde un principio una forma estructurada de código que por ejemplo con python, teniendo más experiencia, se tiende a ir a lo fácil y a lo mejor te puede dar más trabajo luego limpiar todo el código. Te lo dejo completamente a tu elección claro, es una sugerencia personal, lo que prefieras

**Comment by blancagiron** [comment]
Ok, si ves que puede ser mejor Go  a mí me parece genial aprender un lenguaje nuevo y usarlo para el proyecto.
